"""Add semester_name to Semester

Revision ID: b81ee5a6d904
Revises: 7c7bea4962aa
Create Date: 2026-02-02 14:41:48.229790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81ee5a6d904'
down_revision: Union[str, Sequence[str], None] = '7c7bea4962aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semesters', sa.Column('semester_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semesters', 'semester_name')
    # pass
    # ### end Alembic commands ###
